# Generated by Django 4.0.4 on 2022-04-26 17:23

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='global',
            name='registerusers',
        ),
        migrations.AddField(
            model_name='global',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='global',
            name='spam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.spam'),
        ),
    ]
