# Generated by Django 4.0.4 on 2022-04-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_spam_remove_global_registerusers_global_registered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spam',
            old_name='count',
            new_name='mark',
        ),
    ]
