# Generated by Django 4.0.4 on 2022-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_rename_count_spam_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spam',
            name='mark',
        ),
        migrations.AddField(
            model_name='spam',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
