# Generated by Django 4.0.4 on 2022-04-26 19:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_remove_spam_mark_spam_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spam',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
