# Generated by Django 4.0.4 on 2022-04-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_global_registeruser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global',
            name='spam',
        ),
    ]
