# Generated by Django 4.0.4 on 2022-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_remove_global_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='spam',
            field=models.IntegerField(default=0),
        ),
    ]
